"""
Django development settings for aidjangoplatform project.
"""
DEBUG = True

ALLOWED_HOSTS = ['*']

CORS_ALLOW_ALL_ORIGINS = True

# GPT Login Data
AZURE_OPENAI_API_KEY = "7c53126a3d674474a76176d04ad0cfe8"
AZURE_OPENAI_API_BASE = "https://ai-platform-resource-uk-south.openai.azure.com/"
AZURE_OPENAI_API_TYPE = "azure"
AZURE_OPENAI_API_VERSION = "2023-05-15"
AZURE_DEPLOYMENT_NAME_GPT_4 = "GPT-4-UK-SOUTH"
AZURE_DEPLOYMENT_NAME_GPT_4_TURBO = "GPT-4-TURBO-UK-SOUTH"
AZURE_DEPLOYMENT_NAME_GPT_3_5 = "GPT-3-5-UK-SOUTH"
AZURE_DEPLOYMENT_NAME_TEXT_EMBEDDING = "TEXT-EMBEDDING-ADA-UK-SOUTH"
