"""
Django settings for pvs_backend project.

Generated by 'django-admin startproject' using Django 4.2.3.
"""
from .settings_dir.settings_common import *

environment = os.environ.get('ENVIRONMENT', "DEV")

if environment == 'PROD':
    from .settings_dir.settings_production import *
elif environment == "DEV":
    from .settings_dir.settings_development import *


def is_dev() -> bool:
    return environment == 'DEV'


def is_prod() -> bool:
    return environment == 'PROD'
